### PR TITLE
Remove python2-specific documentation

### LINKED ISSUE #85: Update README to reflect python3 only

### PR DESCRIPTION
**Pull request by cthoyt**
Closes #85

### CODE REVIEW

**Comment by UnixJunkie** [comment]
If you remove --with-python3, I am not sure the Python bindings are still built.

**Comment by cthoyt** [comment]
Before you didn't have to specific `--with-python` for python 2, though, did you? If python bindings aren't installed by default without this then I will fix it.

**Comment by UnixJunkie** [comment]
I think they are not build by default.
Same for the java bindings.

**Comment by cthoyt** [comment]
@UnixJunkie I updated it, let me know if that's fine

**Comment by UnixJunkie** [comment]
thanks for help improving the documentation!

**Pull request merged**
