### PR TITLE
More build options

### PR DESCRIPTION
**Pull request by hsiaoyi0504**
As a continuous effort, I updated #57 (see original PR for more detail of the first commit) to this. Now travis test on python 2 as well.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Why do we need pip3 install numpy?
Can't the formula be fully automatic and only rely on other brew formulas?

**Comment by hsiaoyi0504** [comment]
@UnixJunkie Actually, I don't know. As you can see in the `README.md`, there is a conflict before. Maybe it's fixed now, but I don't need this feature and I don't think it's reasonable to install `numpy` by `homebrew`. As you can see in the documentation: https://docs.brew.sh/Python-for-Formula-Authors,
> Homebrew generally won’t accept libraries that can be installed correctly with pip install foo.

**Comment by UnixJunkie** [comment]
OK, but then your formula should do the pip install foos itself.
I.e. be fully automatic.

**Comment by hsiaoyi0504** [comment]
No, I don't think so.

**Comment by hsiaoyi0504** [comment]
Take the way `cython` formula do 
https://github.com/Homebrew/homebrew-core/blob/4c00e62040d56399acb0b0b7c6c87414aac76a7c/Formula/cython.rb

**Comment by hsiaoyi0504** [comment]
@mcs07 Do you have any suggestion on this ?

**Comment by UnixJunkie** [comment]
I mean: if you know that the user has to run 'pip install something' before 'brew install rdkit'.
Then put the 'pip install something' inside your brew formula.
Why require the user to do something that the formula can automatically do?
This is just annoying people for no good reason.

**Comment by hsiaoyi0504** [comment]
Close, I think most of them are fixed in #61.

**Comment by hsiaoyi0504** [comment]
I will open a pull request again for also building under python 2.

**Pull request closed without merging**
