### PR TITLE
Added Cairo support

### LINKED ISSUE #103: Add build with Cairo flag
You need to add `args << '-DRDK_BUILD_CAIRO_SUPPORT=ON' if build.with? "pycairo"` in order to build with Cairo.

### PR DESCRIPTION
**Pull request by thorlucas**
Fixes #103

### CODE REVIEW

**Comment by UnixJunkie** [comment]
related to https://github.com/rdkit/homebrew-rdkit/issues/103

**Comment by UnixJunkie** [comment]
thanks a lot

**Comment by thorlucas** [comment]
I would also add this flag to the README so people know that they can’t access the Cairo drawer without it 👍 @UnixJunkie

**Comment by UnixJunkie** [comment]
Done, you should follow the github project if you want to get notifications about commits.

**Pull request merged**
