### PR TITLE
fix-travis

### PR DESCRIPTION
**Pull request by hsiaoyi0504**
Fix travis, the build now succeeds.
https://travis-ci.org/hsiaoyi0504/homebrew-rdkit/builds/316046596

@greglandrum

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Hello,

Shouldn't those be part of the formula in some way:

    brew install python3
    pip2 install numpy
    pip3 install numpy

Regards,
F.

**Comment by hsiaoyi0504** [comment]
@UnixJunkie I don't get it. These lines are not included in the homebrew formula.

**Comment by UnixJunkie** [comment]
Dear Hsiaoyi,

The brew formula is supposed to be automatic.
You cannot ask people to read something before they type 'brew install rdkit'.
'brew install rdkit' should work out of the box.

I guess python3 is a dependency of the brew rdkit formula.
Then, numpy should be installed by pip2 and pip3, I believe all of those three things
can go into the brew formula.

Recently, I learnt that 'brew install rdkit' doesn't work because of some
failing continuous integration tests (which are just using 'brew install rdkit').

Regards,
Francois.

**Comment by hsiaoyi0504** [comment]
@UnixJunkie I totally agree that it would be good to be table to install rdkit through homebrew out of the the box. However, the dependency issues are everywhere. Homebrew doesn't fully constrain how user uses python.  Therefore, this formula provide different options to make it work for as many people as possible. The introduce of the Travis here is for easy access current status of the formula.  It just a simple start, and I will try my best extending it to most use cases, but in short term, I will not touch much about the formula itself (because I am not quite familiar with that). I will construct the Travis CI system to monitor the health state of the formula first. If you have good ideas about this, welcome you to make PRs to contribute.

**Comment by UnixJunkie** [comment]
A good thing would be that the formula works well from a fresh install.
I.e. the user has just installed brew (not numpy and python; those should be installed by the formula, if needed).
Then he just types in 'brew install rdkit'.
I will try to help improve the formula, if I can and when I am in front of a Mac (which is rare).
It is great that there is some continuous integration testing of this, excellent work!

**Comment by hsiaoyi0504** [comment]
@UnixJunkie 
If you have interested, you can also check this build:
https://travis-ci.org/hsiaoyi0504/homebrew-rdkit/jobs/316268436

**Pull request merged**
