### PR TITLE
Add c++11 support, deprecate EOS.undent

### PR DESCRIPTION
**Pull request by bp-kelley**

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum This should work, I'm unsure of the tag/release to use though.

**Comment by bp-kelley** [comment]
Even though this timed out, it apparently works.

**Comment by bp-kelley** [comment]
Freaking finally.

**Comment by greglandrum** [comment]
Nice. thanks for doing this.

Not something for this PR, but it would cool if we could modify the travis job to add something to check that the install actually did something (as opposed to just running without failing)

**Comment by UnixJunkie** [comment]
@bp-kelley Hello, do you have a sequence of shell commands to recommend in order to reproducibly install rdkit using brew on a blank mac os x (as in a freshly booted OS image in a CI tests environment)?
Thanks a lot,
F.

**Pull request merged**
