### PR TITLE
 Migrate to pip method of Python package install

### PR DESCRIPTION
**Pull request by maksbotan**
This is a follow-up to https://github.com/rdkit/rdkit/pull/2690

For demonstration, HEAD URL was changed to my branch. It must be changed back once RDKit PR is merged, along with URL to the new release.

### CODE REVIEW

**Comment by UnixJunkie** [comment]
Why do you use pip instead of pip3?
Python2 is no more supported by rdkit and
pip is the installer for python2 packages.

**Comment by maksbotan** [comment]
First of all, take a look at the rdkit pr I linked. Then, notice that I do not call pip directly, but rather with `#{python_executable} -m pip`, which selects just right pip (that's how the module is called in python 3 as well) for brew's python.

**Comment by UnixJunkie** [comment]
Ok.
You should try updating the .travis.yml file in your PR.

**Comment by maksbotan** [comment]
No problem, will do today.

**Comment by UnixJunkie** [comment]
In another issue, the submitter said that this PR is no more necessary.

**Pull request closed without merging**
